name: Manual Input to CSV

on:
  workflow_dispatch:
    inputs:
      product:
        type: choice
        description: 'Directory Name of the Product'
        required: true
        options:
          - AMD_MI100
          - ARUBA_CX6300_CX6400
          - ARUBA_CX8320
          - ARUBA_CX8325
          - ARUBA_CX8360
          - GB_SVR_1264UP_C37
          - GB_SVR_3264_C37
          - GB_SVR_5264_C37
          - HPE_EX235a
          - HPE_EX235N
          - HPE_EX420
          - HPE_EX425
          - HPE_EX425_Gen2
          - INT_i210
          - MTN_CCNC
          - Other
      location:
        description: 'Select the dev firmware location'
        type: choice
        options:
          - Morpheus
          - Artifactory
        required: true
      link:
        description: 'Enter the link'
        required: true
      product_name:
        description: 'Enter product name'
        required: true
      version:
        description: 'Enter product version'
        required: true
      type:
        description: 'Enter product type'
        type: choice
        required: true
        options:
          - rpm
          - swi
          - scexe
          - fwpkg
          - tar.gz
          - bin

jobs:
  save-to-csv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    - name: Create or Append to CSV
      run: |
        # Check if the CSV file exists, if not create it
        if [ ! -f data.csv ]; then
          echo "Product,location,link,ProductName,Version,Type" > data.csv
        fi
        # Append the new data
        echo "${{ github.event.inputs.product }},${{ github.event.inputs.location }},${{ github.event.inputs.link }},${{ github.event.inputs.product_name }},${{ github.event.inputs.version }},${{ github.event.inputs.type }}" >> data.csv
    - name: Pull latest repo
      run: |
        git config --local user.email "akashsangnure0586@gmail.com"
        git config --local user.name "GitHub Actions"
        # Pulling original
        git pull origin main || true
 
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "No changes made"
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "Changes made"
          echo "changes_detected=true" >> $GITHUB_ENV
          # Do not exit with 1; instead, you can just continue
        fi
      continue-on-error: true

 
    - name: Commit changes to csv if there are any
      if: steps.changes.outcome == 'failure'  # Making sure there are changes
      run: |
        git add data.csv
        git commit -m "adding to csv"
 
    - name: Commit Changes
      if: env.changes_detected == 'true'  # Only run if changes are detected
      run: |
        git config --local user.email "akashsangnure0586@gmail.com"
        git config --local user.name "GitHub Actions"
        git add data.csv

        # Check for changes before committing
        if ! git diff --cached --quiet; then
          git commit -m "adding to csv file"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/akash-ashok-sangnure/DEV-HFP.git HEAD:main
        else
          echo "No changes to commit, skipping commit step."
        fi
